# Permalinks
permalink:           pretty

# Setup
title:               Code Better World
tagline:             
url:                 http://codebetterworld.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nathan Luu
  url:               
  email:             nate1299@me.com

# Custom vars
version:             2.0.0
github:
  repo:              

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
